[[ftable_AnchorBerth]]
=== Anchor Berth

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# A designated area of water where a vessel, sea plane, etc., may anchor. +
Remarks: In general the anchor berth is defined by the centre point and a swinging circle radius.
8+h| [underline]#S-131 Geo Feature:# AnchorBerth
8+h| [underline]#Super Type:# Layout
8+h| [underline]#Primitives:# point surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Category of Anchorage |
2+|1: Unrestricted Anchorage +
2: Deep Water Anchorage +
3: Tanker Anchorage +
5: Quarantine Anchorage +
6: Seaplane Anchorage +
7: Small Craft Anchorage +
10: Anchorage for a Limited Period of Time +
14: Waiting Anchorage +
 |EN | 0,*

3+| Category of Cargo |
2+|1: Bulk +
2: Container +
3: General +
4: Liquid +
5: Passenger +
6: Livestock +
7: Dangerous or Hazardous +
8: Heavy Lift +
9: Ballast +
10: Dry Bulk Cargo +
11: Liquid Bulk Cargo +
12: Reefer Container Cargo +
13: Ro-Ro Cargo +
14: Project Cargo +
15: Break Bulk Cargo +
 |EN | 0,*

3+| Radius |
2+| |RE | 0,1

8+h| Inherited Attributes

3+h|S-131Attribute 3+h| Inherited From h| Type h| Multiplicity

3+| Location Maritime Resource Name 3+| FeatureType | URN | 0,1
3+| Global Location Number 3+| FeatureType | TE | 0,1
3+| Interoperability Identifier 3+| FeatureType | URN | 0,*
3+| Feature Name 3+| FeatureType | C | 0,*
3+| Fixed Date Range 3+| FeatureType | C | 0,1
3+| Periodic Date Range 3+| FeatureType | C | 0,*
3+| RxN Code 3+| FeatureType | C | 0,*
3+| Graphic 3+| FeatureType | C | 0,*
3+| Source Indication 3+| FeatureType | C | 0,*
3+| Text Content 3+| FeatureType | C | 0,*
3+| Scale Minimum 3+| FeatureType | IN | 0,1
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.

|serviceDescriptionReference|ServiceAvailability|AvailablePortServices|association|0,1
|facilityOperatingHours|LocationHours|ServiceHours|association|0,1
|controlAuthority|ServiceControl + 
(inherited from SupervisedArea) |Authority|association|0,1
|theContactDetails|ServiceContact + 
(inherited from OrganizationContactArea) |ContactDetails|association|0,*
|permission|PermissionType + 
(inherited from FeatureType) |Applicability|association|0,*
|theRxN|AssociatedRxN + 
(inherited from FeatureType) |AbstractRxN|association|0,*
|theInformation|AdditionalInformation + 
(inherited from FeatureType) |NauticalInformation|association|0,*
|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|auxiliaryFacility|PrimaryAuxiliaryFacility|MooringWarpingFacility|association|0,*
|theCartographicText|TextAssociation + 
(inherited from FeatureType) |TextPlacement|association|0,1
|===


include::../instructions/AnchorBerth.adoc[]
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _rxNCode_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.

