[[ftable_Entrance]]
=== Entrance

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# The seaward end of a channel, harbour, dock, etc.
8+h| [underline]#S-131 Information Type:# Entrance
8+h| [underline]#Super Type:# InformationType
3+h| S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
            
3+| Entrance Description |
2+| |TE | 0,1

3+| Associated Feature Name |
2+| |TE | 0,*

3+| Local Knowledge Description |
2+| |TE | 0,1

3+| Approach Description |
2+| |TE | 0,1

3+| Marked By | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
3+| Landmark Description | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
3+| Offshore Mark Description | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
3+| Major Light Description | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
3+| Useful Mark Description | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
3+| Text Content | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Category of Text |
2+|1: Abstract or Summary +
2: Extract +
3: Full Text +
 |(S) EN | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Information | 2+| | (S)  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;Online Resource | 2+| | (S)  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Source Indication | 2+| | (S)  C | 0,*
8+h| Inherited Attributes

3+h| S-131 Attribute 3+h| Inherited From h| Type h| Multiplicity
            
3+| Feature Name 3+| InformationType | C | 0,*
3+| Fixed Date Range 3+| InformationType | C | 0,1
3+| Periodic Date Range 3+| InformationType | C | 0,*
3+| Graphic 3+| InformationType | C | 0,*
3+| Source Indication 3+| InformationType | C | 0,*
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|===


include::../instructions/Entrance.adoc[]
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.

