[[ftable_HarbourAreaSection]]
=== Harbour Area Section

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# A distinguishable portion of the area over which a harbour authority has jurisdiction. +
Remarks: Denotes a specific, distinguishable or designated portion of a harbour or port area, as distinct from the entire harbour or port area.
8+h| [underline]#S-131 Geo Feature:# HarbourAreaSection
8+h| [underline]#Super Type:# Layout
8+h| [underline]#Primitives:# point surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Category of Port Section |
2+|1: Port Fairway +
3: Berth Pocket +
8: Seaplane Anchorage +
9: Dredged Basin +
11: Port Safety Zone +
12: Lay-by Berth +
 |EN | 0,1

3+| Category of Harbour Facility |
2+|4: Fishing Harbour +
5: Yacht Harbour/Marina +
6: Naval Base +
9: Shipyard +
14: Service Harbour +
15: Pilotage Service +
16: Service and Repair +
17: Quarantine Station +
 |EN | 0,*

3+| ISPS Level |
2+|1: ISPS Level 1 +
2: ISPS Level 2 +
3: ISPS Level 3 +
 |EN | 0,1

3+| Facilities Layout Description | 2+| |  C | 0,1
3+| &nbsp;&nbsp;&nbsp;&nbsp;Text Content | 2+| | (S)  C | 1,*
8+h| Inherited Attributes

3+h|S-131Attribute 3+h| Inherited From h| Type h| Multiplicity

3+| Location Maritime Resource Name 3+| FeatureType | URN | 0,1
3+| Global Location Number 3+| FeatureType | TE | 0,1
3+| Interoperability Identifier 3+| FeatureType | URN | 0,*
3+| Feature Name 3+| FeatureType | C | 0,*
3+| Fixed Date Range 3+| FeatureType | C | 0,1
3+| Periodic Date Range 3+| FeatureType | C | 0,*
3+| RxN Code 3+| FeatureType | C | 0,*
3+| Graphic 3+| FeatureType | C | 0,*
3+| Source Indication 3+| FeatureType | C | 0,*
3+| Text Content 3+| FeatureType | C | 0,*
3+| Scale Minimum 3+| FeatureType | IN | 0,1
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.

|serviceDescriptionReference|ServiceAvailability|AvailablePortServices|association|0,1
|facilityOperatingHours|LocationHours|ServiceHours|association|0,1
|controlAuthority|ServiceControl + 
(inherited from SupervisedArea) |Authority|association|0,1
|theContactDetails|ServiceContact + 
(inherited from OrganizationContactArea) |ContactDetails|association|0,*
|permission|PermissionType + 
(inherited from FeatureType) |Applicability|association|0,*
|theRxN|AssociatedRxN + 
(inherited from FeatureType) |AbstractRxN|association|0,*
|theInformation|AdditionalInformation + 
(inherited from FeatureType) |NauticalInformation|association|0,*
|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|componentOf|LayoutDivision|HarbourAreaAdministrative|aggregation|0,1
|constitute|Subsection|HarbourAreaSection|aggregation|0,1
|subUnit|Subsection|HarbourAreaSection|association|0,*
|hasInfrastructure|Infrastructure|HarbourPhysicalInfrastructure|association|0,*
|layoutUnit|LayoutDivision|AnchorageArea Berth DockArea DumpingGround FenderLine HarbourBasin PilotBoardingPlace SeaplaneLandingArea Terminal TurningBasin WaterwayArea|association|0,*
|theCartographicText|TextAssociation + 
(inherited from FeatureType) |TextPlacement|association|0,1
|===


include::../instructions/HarbourAreaSection.adoc[]
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _rxNCode_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.

