[[ftable_SoundingDatum]]
=== Sounding Datum

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# The horizontal plane or tidal datum to which soundings have been reduced. Also called datum for sounding reduction.
8+h| [underline]#S-131 Geo Feature:# SoundingDatum
8+h| [underline]#Super Type:# 
8+h| [underline]#Primitives:# surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Vertical Datum |
2+|1: Mean Low Water Springs +
2: Mean Lower Low Water Springs +
3: Mean Sea Level +
4: Lowest Low Water +
5: Mean Low Water +
6: Lowest Low Water Springs +
7: Approximate Mean Low Water Springs +
8: Indian Spring Low Water +
9: Low Water Springs +
10: Approximate Lowest Astronomical Tide +
11: Nearly Lowest Low Water +
12: Mean Lower Low Water +
13: Low Water +
14: Approximate Mean Low Water +
15: Approximate Mean Lower Low Water +
19: Approximate Mean Sea Level +
22: Equinoctial Spring Low Water +
23: Lowest Astronomical Tide +
24: Local Datum +
25: International Great Lakes Datum 1985 +
26: Mean Water Level +
27: Lower Low Water Large Tide +
44: Baltic Sea Chart Datum 2000 +
 |EN | 1,1

3+| Information | 2+| |  C | 0,*
3+| &nbsp;&nbsp;&nbsp;&nbsp;File Locator |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;File Reference |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Headline |
2+| |(S) TE | 0,* (ordered)

3+| &nbsp;&nbsp;&nbsp;&nbsp;Language |
2+| |(S) TE | 0,1

3+| &nbsp;&nbsp;&nbsp;&nbsp;Text |
2+| |(S) TE | 0,1

8+h| Inherited Attributes

3+h|S-131Attribute 3+h| Inherited From h| Type h| Multiplicity

8+h| No inherited attributes
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.

|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|===


include::../instructions/SoundingDatum.adoc[]
* If the complex attribute _information_ is present at least one of its sub-attributes must be populated.

