[[ftable_SupervisedArea]]
=== Supervised Area

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# A location which may be supervised by a responsible or controlling authority. +
Remarks: It is not a requirement that every feature instance be associated with an authority. Note that having AbstractService as well as SupervisedArea allows the subclasses to link to CONDET both directly and via AUTORI, which may not be desirable because it gives encoders two ways to reach almost the same result.
8+h| [underline]#S-131 Geo Feature:# SupervisedArea (Abstract)
8+h| [underline]#Super Type:# OrganizationContactArea
8+h| [underline]#Primitives:# noGeometry
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
8+h| Inherited Attributes

3+h|S-131Attribute 3+h| Inherited From h| Type h| Multiplicity

3+| Location Maritime Resource Name 3+| FeatureType | URN | 0,1
3+| Global Location Number 3+| FeatureType | TE | 0,1
3+| Interoperability Identifier 3+| FeatureType | URN | 0,*
3+| Feature Name 3+| FeatureType | C | 0,*
3+| Fixed Date Range 3+| FeatureType | C | 0,1
3+| Periodic Date Range 3+| FeatureType | C | 0,*
3+| RxN Code 3+| FeatureType | C | 0,*
3+| Graphic 3+| FeatureType | C | 0,*
3+| Source Indication 3+| FeatureType | C | 0,*
3+| Text Content 3+| FeatureType | C | 0,*
3+| Scale Minimum 3+| FeatureType | IN | 0,1
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.

|controlAuthority|ServiceControl|Authority|association|0,1
|theContactDetails|ServiceContact + 
(inherited from OrganizationContactArea) |ContactDetails|association|0,*
|permission|PermissionType + 
(inherited from FeatureType) |Applicability|association|0,*
|theRxN|AssociatedRxN + 
(inherited from FeatureType) |AbstractRxN|association|0,*
|theInformation|AdditionalInformation + 
(inherited from FeatureType) |NauticalInformation|association|0,*
|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|theCartographicText|TextAssociation + 
(inherited from FeatureType) |TextPlacement|association|0,1
|===


include::../instructions/SupervisedArea.adoc[]
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _rxNCode_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.

