[[ftable_Terminal]]
=== Terminal

[cols="a,a,a,a,a,a,a,a",options="headers,unnumbered"]
|===
8+| [underline]#IHO Definition:# A terminal covers that area on shore which provides buildings and constructions for the transfer of cargo or passengers from and to ships.
8+h| [underline]#S-131 Geo Feature:# Terminal
8+h| [underline]#Super Type:# Layout
8+h| [underline]#Primitives:# point surface
3+| _Real World_ 2+| _Paper Chart Symbol_ 3+| _ECDIS Symbol_
3+h|S-131 Attribute h| S-57 Acronym 2+h| Allowable Encoding Value h| Type h| Multiplicity
3+| Port Facility Number |
2+| |TE | 0,1

3+| Category of Terminal |
2+|1: RoRo Terminal +
3: Ferry Terminal +
7: Tanker Terminal +
8: Passenger Terminal +
10: Container Terminal +
11: Bulk Terminal +
 |EN | 0,1

3+| Category of Cargo |
2+|3: General +
4: Liquid +
6: Livestock +
7: Dangerous or Hazardous +
8: Heavy Lift +
10: Dry Bulk Cargo +
11: Liquid Bulk Cargo +
12: Reefer Container Cargo +
14: Project Cargo +
15: Break Bulk Cargo +
 |EN | 0,*

3+| Product |
2+|1: Oil +
2: Gas +
4: Stone +
5: Coal +
6: Ore +
7: Chemicals +
9: Milk +
10: Bauxite +
11: Coke +
12: Iron Ingots +
13: Salt +
14: Sand +
15: Timber +
16: Sawdust/Wood Chips +
17: Scrap Metal +
18: Liquefied Natural Gas +
19: Liquefied Petroleum Gas +
20: Wine +
21: Cement +
22: Grain +
 |EN | 0,*

3+| Terminal Identifier |
2+| |TE | 0,1

3+| SMDG Terminal Code |
2+| |TE | 0,1

3+| UN Location Code |
2+| |TE | 0,1

8+h| Inherited Attributes

3+h|S-131Attribute 3+h| Inherited From h| Type h| Multiplicity

3+| Location Maritime Resource Name 3+| FeatureType | URN | 0,1
3+| Global Location Number 3+| FeatureType | TE | 0,1
3+| Interoperability Identifier 3+| FeatureType | URN | 0,*
3+| Feature Name 3+| FeatureType | C | 0,*
3+| Fixed Date Range 3+| FeatureType | C | 0,1
3+| Periodic Date Range 3+| FeatureType | C | 0,*
3+| RxN Code 3+| FeatureType | C | 0,*
3+| Graphic 3+| FeatureType | C | 0,*
3+| Source Indication 3+| FeatureType | C | 0,*
3+| Text Content 3+| FeatureType | C | 0,*
3+| Scale Minimum 3+| FeatureType | IN | 0,1
|===

[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Information associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.

|serviceDescriptionReference|ServiceAvailability|AvailablePortServices|association|0,1
|facilityOperatingHours|LocationHours|ServiceHours|association|0,1
|controlAuthority|ServiceControl + 
(inherited from SupervisedArea) |Authority|association|0,1
|theContactDetails|ServiceContact + 
(inherited from OrganizationContactArea) |ContactDetails|association|0,*
|permission|PermissionType + 
(inherited from FeatureType) |Applicability|association|0,*
|theRxN|AssociatedRxN + 
(inherited from FeatureType) |AbstractRxN|association|0,*
|theInformation|AdditionalInformation + 
(inherited from FeatureType) |NauticalInformation|association|0,*
|===


[cols="a,a,a,a,a",options="headers,unnumbered"]
|===
5+h| *Feature associations*

h|S-131 Role	h|S-131 Association Name h| Associated to h| Type	h| Mult.
|componentOf|LayoutDivision|HarbourAreaSection|aggregation|1,1
|layoutUnit|LayoutDivision|Berth|association|0,*
|hasInfrastructure|Infrastructure|HarbourPhysicalInfrastructure|association|0,*
|theCartographicText|TextAssociation + 
(inherited from FeatureType) |TextPlacement|association|0,1
|===


include::../instructions/Terminal.adoc[]
* If the complex attribute _fixedDateRange_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _rxNCode_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _sourceIndication_ is present at least one of its sub-attributes must be populated.
* If the complex attribute _textContent_ is present at least one of its sub-attributes must be populated.
** If the _textContent_ sub-attribute _information_ is present at least one of its sub-attributes must be populated.

