
[[sec_6]]
== Coordinate Reference Systems (CRS)

[[sec_6.1]]
=== Introduction

An MHI dataset must define one geodetic CRS and one vertical CRS each for depths and elevations.


The location of an object in the S-100 standard is defined by means
of coordinates which relate a feature to a position. The coordinate
reference system used for this product specification is World Geodetic
System 1984 (WGS 84) which is defined by the European Petroleum Survey
Group (EPSG) code 4326, (or similar - North American Datum 1983 /
Canadian Spatial Reference System).

Spatial data are expressed as latitude (stem:[varphi]) and longitude
(stem:[lambda]) geographic
coordinates. Latitude values are stored as a negative number to represent
a position south of the Equator. Longitude values are stored as a
negative number to represent a position west of the Prime Meridian.
Coordinates are expressed as real value, degree / degree decimal format.
Datasets conforming to this product specification are not projected.

[[sec_6.2]]
=== Horizontal Coordinate Reference System

The horizontal CRS must be EPSG 4326 (WGS84). The full reference to
EPSG 4326 can be found at https://epsg.org/home.html.

*Horizontal Coordinate Reference System:*:: EPSG 4326 (WGS84)

*Projection:*:: None

*Temporal reference system:*:: Gregorian calendar

*Coordinate Reference System registry:*:: EPSG Geodetic Parameter Registry

*Date type (according to <<ISO_19115_1>>):*:: 002 - publication

*Responsible party:*:: International Organisation of Oil and Gas Producers (IOGP)

*URL:*:: https://epsg.org/home.html

[[sec_6.3]]
=== Vertical CRS for Depths and Elevations

The vertical CRS must be in metres. Depths are represented by positive
values, while negative values indicate intertidal (drying) soundings
(for depths).

Depths and elevations may be referenced to different vertical datums.
The vertical datum for each must be encoded in a meta-feature
(*SoundingDatum* for depths and *VerticalDatumOfData* for elevations).
There should be only one vertical datum for all depths and only one
for all elevations.

The vertical coordinate reference systems specified in *SoundingDatum* and *VerticalDatumOfData* must be chosen so that the vertical axis directions are downward-positive 
for the CRS in *SoundingDatum* and upward-positive for the CRS in *VerticalDatumOfData*.

[[sec_6.4]]
=== Projections

MHI datasets are un-projected.

[[sec_6.5]]
=== Temporal reference system

Time is measured by reference to Calendar dates and Clock time in
accordance with <<ISO_19108_2002,clause=5.4.4>>, Temporal Schema.

[[sec_6.6]]
=== Marine Harbour Infrastructure data and scale

MHI data must be compiled in the best applicable scale.

MHI datasets may be scale-dependent in that features may be compiled at a scale determined
by data producer depending on the intended use of the dataset and spatial primitives may depend
on the compilation scale. For example, detailed port features may be encoded as points in small-scale
datasets but as polygons (surfaces) in large scale datasets.

The primary intended use of S-131 being for port information, most MHI datasets are expected to be large-scale datasets.

S-100 allows the association of multiple spatial
attributes to a single feature instance. In principle, each of these
spatial attributes can be qualified by maximum and minimum scales.

For example, it is possible, within one dataset, to have a single
instance of a feature that has more than one area geometry. Each of
these geometries has different scale max/min attributes. Moreover,
due to cluttering in smaller scales, the scale minimum attribute may
be used to turn off portrayal of some features at smaller scales.
