
[[sec_maint]]
== Maintenance

[[sec_maint.1]]
=== Introduction

This clause describes the requirement to adequately maintain datasets;
use of newly acquired source data; maintenance requirements within
the overall production process; and how Feature and Portrayal Catalogues
are to be managed within an S-100 based marine navigation system.

[[sec_maint.2]]
=== Maintenance and update frequency

Datasets must be maintained as needed; and the overall production
process must include mechanisms for updating designed to meet the
needs of the mariner regarding safety of navigation.

[[sec_maint.3]]
=== Data Source

Data Producers must use all available and applicable sources, as evaluated
against a robust data assessment process, to maintain and update datasets
as required.

[[sec_maint.4]]
=== Production Process

Data Producers should follow their established production processes
for maintaining and updating datasets. Data must be maintained against
S-131 Annex A -- _Data Classification and Encoding Guide_, checked
against validation checksin S-158:100 and S-158:131 (generic and product-specifc validation checks respectively), and encapsulated in
GML conforming to the S-131 GML schema.

[[sec_maint.5]]
=== Dataset updates and cancellation

The purpose of issue of the dataset is indicated in the "purpose"
field of the dataset discovery metadata. Cancellation used the file-less
cancellation method described in S-100 Part 17.

Where a dataset is cancelled and its name is reused at a later date,
the issue date must be greater than the issue date of the cancelled
dataset.

When the dataset is cancelled it must be removed from the system along
with all related update datasets and support files.

An exchange set may contain base dataset files and update dataset
files for the same datasets. Under these circumstances the update
dataset files must follow in the correct sequential order from the
last update applied to the base dataset file.

[[sec_maint.6]]
=== Support file updates

The purpose of issue is indicated in the "purpose" field of the support
file discovery metadata. Support files carrying the "deletion" flag
in metadata must be removed from the system. When a feature or information
type pointing to a text, picture, or application file is deleted or
updated so that it no longer references the file, the system software
must check to see whether any other feature or information type references
the same file before that file is deleted.

Updates or deletions of a support file may require concurrent updates
to feature or information type instance attributes that depend on
the file, e.g., pictorialRepresentation, fileReference, and fileLocator
attributes.

[[sec_maint.7]]
=== Feature and Portrayal Catalogue management

For each new version of the S-131 Product Specification a new Feature
and Portrayal Catalogue will be released. The end user system must
be able to manage datasets and their corresponding Catalogues that
are created using different versions of the S-131 Product Specification.

[[sec_maint.8]]
=== Feature history, versions, and change tracking

If applications or production systems require versioning of individual
instances of feature or information types, maintenance of histories,
or change tracking, the methods for versioning, history management,
and change tracking and display are left to the application or production
system.

[[sec_maint.9]]
=== Dataset encryption

Encryption of datasets is at producer discretion. S-100 Part 15 and IHO publication S-63 describe the IHO scheme
for data protections.
