

[[sec_12]]
== Data Product format (encoding)

[[sec_12.1]]
=== Format specification

The format for datasets must conform to the S-131 GML schema specified
below. See S-100 Part 10b and the S-131 GML schema documentation for
a complete description of the data records, fields and subfields defined
in the encoding.

[[table_.1]]
.Format specification information
[cols="82,305,194"]
|===
h| Name h| ISO 19131 Elements h| Value

| Format name | DPS_DeliveryInformation.deliveryFormat > DPS_DeliveryFormat.formatName | GML
| Version     | DPS_DeliveryInformation.deliveryFormat > DPS_DeliveryFormat.version    | 3.2.1
| Specification description | DPS_DeliveryInformation.deliveryFormat > DPS_DeliveryFormat.specification
| S-100 profile of GML (S-100 Part 10b)
| Language | DPS_DeliveryInformation.deliveryFormat > DPS_DeliveryFormat.language | English
| Character set | DPS_DeliveryInformation.deliveryFormat > DPS_DeliveryFormat.characterSet > MD_CharacterSetCode | 004 -- utf8
| Additional Information | DPS_DeliveryInformation.additionalInformation > DPS.AdditionalInformation.additionalInformation
| GML schema for S-131 Edition 2.0.0 (https://schemas.s100dev.net)

|===

[[sec_12.2]]
=== Encoding of latitude and longitude

Values of latitude and longitude must be accurate to 7 decimal places.
Coordinates must be encoded as decimals in the format described below.

* Values should be coded as decimal numbers with 7 or fewer digits
after the decimal. The normative encoding is in degrees, with an accuracy
of stem:[10^{-7}] degrees, i.e., 7 digits after the decimal point.
* The decimal point must be indicated by the "." character.
* Trailing zeroes after the decimal point (and the decimal point itself
if appropriate) may be omitted at producer discretion, but the accuracy
must still be as indicated (e.g., stem:[10^{-7}] degrees for coordinates
of default accuracy).

[[sec_12.3]]
=== Encoding of depths

Depths are encoded in the format and precision specified in the feature
catalogue for the corresponding attribute. Positive values indicate
distances below the applicable datum reference.

[[sec_12.4]]
=== Numeric attribute encoding

Integer attribute values must not contain leading zeros.

Floating point attributes must not contain leading zeros. Values in
the interval (-1, 1) may use a single zero before the decimal point.

Floating point attribute values must not contain non-significant trailing
zeros exceeding the attribute's precision as specified in the feature
catalogue.

[[sec_12.5]]
=== Text attribute values

Character strings must be encoded using the character set defined
in <<ISO_10646_1>>, in Unicode Transformation Format-8 (UTF-8).

[[sec_12.6]]
=== Mandatory attribute values

There are four reasons why attribute values may be considered mandatory:

* They determine whether a feature is in the display base,

* Certain features make no logical sense without specific attributes,

* Some attributes are necessary to determine which symbol is to be
displayed,

* Some attributes are required for safety of navigation.

All mandatory attributes are identified in the Feature Catalogue and
summarised in the Data Classification and Encoding Guide.

[[sec_12.7]]
=== Unknown attribute values

When an attribute code is present but the attribute value is missing,
it means that the producer wishes to indicate that this attribute
value is unknown.

[[sec_12.8]]
=== Object identifiers

Feature records must have a unique world-wide identifier. When an
MRN naming scheme is finalised by IHO, the identifier must be derived
from the MRN of the feature by a reversible 1/1 mapping (i.e., each
identifier must map to a corresponding unique MRN and each MRN must
map to a corresponding unique feature identifier).

MRN identifiers are not included in this version due to ongoing development
of the IHO guidelines in the use of MRN for product specifications.

Features, information types, collection objects, meta features, and
geometries (inline or external) are all required by the schema to
have a gml:id attribute with a value that is unique within the dataset.
The gml:id values must be used as the reference for the object from
another object in the same dataset or another dataset.

[[sec_12.9]]
=== Data coverage

All areas of a dataset must be covered by a *DataCoverage* meta feature.

An update dataset must not change the limit of a *DataCoverage* feature
for the base dataset. Where the limit of a *DataCoverage* feature
for a base dataset is to be changed, this must be done by issuing
a new edition of the dataset.

[[sec_12.10]]
=== Data overlap

S-131 datasets must not overlap other S-131 datasets of the same scale
range.

[[sec_12.11]]
=== Data quality meta-features

One or more *QualityOfNonBathymetricData* features must cover the
dataset.

[[sec_12.12]]
=== Data extent

Datasets must not cross the 180° meridian of longitude.

[[sec_12.13]]
=== Sequence of objects

The following sequence of objects is recommended:

[pseudocode%unnumbered]
====
Spatial records for by-reference geometries
    Point
    Multi point
    Curve
    Composite Curve
    Surface
Information objects
Feature objects
    Meta features
    Geo features
====

[[sec_12.14]]
=== Content of update datasets

Update datasets can only contain replacements, deletions, and additions
of whole feature instances or information instances. This means that
when a feature or information instance is updated, the new version
must contain all the attributes of the old instance, including any
inline spatial attributes (i.e., inline geometry), except those attributes
that are being removed.

An association to an instance of a feature or information type is
treated as an attribute of the referring instance, and therefore adding
or deleting an association means the original referring instance must
be replaced with a new version. The instance at the other end of the
association needs to be replaced if and only if it contains a reference
to the first instance.

Spatial objects that are not inline (i.e., geometry that is encoded
as an independent spatial object in the dataset) is treated like any
other object, i.e., it needs to be updated if and only if the primitive
has changed (e.g., a coordinate is updated).

Feature and information type instances are deleted without replacement
by setting the *fixedDateRange*.*dateEnd* attribute of the instance
to the date of deletion, which will usually be the issue date of the
update.

[[sec_12.15]]
=== Datum coverage

All features in a dataset with depth or elevation attributes must
be covered by *SoundingDatum* and *VerticalDatumOfData* meta-features
respectively.

[[sec_12.16]]
=== Attribute multiplicity

In general, if all the sub-attributes of a complex attribute are optional,
at least one of them must be present and have a value that is not
empty (or white space, for attributes of type "text" or types derived
from "text").

Similarly, if all the attributes of an information type are optional,
at least one of them must be present and have a non-empty value.

Note that there is no such general rule for features, though the DCEG
may require it for specific features.

EDITOR: These requirements were phrased as recommendations in Edition 1.0 in
order to facilitate the phased development of datasets. Future editions
may strengthen them as appropriate. (Done in 2.0.0)
