==== General

*LockBasinPart* is used if and only if a lock is divided into several parts, otherwise a single *LockBasin* feature must be encoded.

If a lock basin has more than two gates and the ground level is the same, different lock basin parts must be created.

If the lock basin part has a special time schedule or special operating hours apply, working times can be encoded using the working times model in
S-131 (see clauses <<sec_2.4.10.4,droploc%>> and <<sec_WorkSchedules,droploc%>>).

The sill depth for each *LockBasinPart* may be encoded using the optional _sillDepth_ attribute.

The attribute _interoperabilityIdentifier_ should be used to link an S-131 *LockBasinPart* feature to the corresponding S-101 *LockBasin* features if any as well
as the corresponding S-401 *LockBasinPart* features, if any.

[[sec_AggregratedLockBasins]]
===== Aggregations of lock basin parts in a common lock system

A covering *LockBasin* feature should be encoded if it is necessary to encode information that applies uniformly to all lock basin parts or to the lock system
as a whole, such aa a common operating schedule, name, single global location number, MRN, etc.

===== Notes on source materials

Lock Basin Part features are used in inland navigation charts (see S-401 - IEHG INLAND ELECTRONIC NAVIGATIONAL CHART PRODUCT SPECIFICATION - Edition 1.2.0).

S-401 requires that all features which belong to one lock must be associated to a Lock Aggregation. There is no equivalent aggregation feature or
aggregration relationship in the S-131 Application Schema, but a covering *LockBasin* feature *must* be encoded to hold common attributes and associations
(clause <<sec_AggregratedLockBasins,droploc%>>).

If the *LockBasinPart* features have no information in common, a covering *LockBasin* feature *may* be encoded.

==== Remarks

